apiVersion: v1
kind: Secret
metadata:
  name: {{ include "full-template.fullname" . }}-secrets
  labels:
    {{- include "full-template.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  zarinpal-merchant-id: {{ .Values.secrets.zarinpalMerchantId | b64enc }}
  vandar-api-key: {{ .Values.secrets.vandarApiKey | b64enc }}
  senator-api-key: {{ .Values.secrets.senatorApiKey | b64enc }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | b64enc }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | b64enc }}
